apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgsql-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgsql-pvc
  labels:
    app: unethicalite
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unethicalite-pgsql
  labels:
    app: unethicalite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unethicalite
      tier: pgsql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: unethicalite
        tier: pgsql
    spec:
      containers:
        - name: unethicalite-pgsql
          image: postgres:11-alpine
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
              name: pgsql
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: pgsql-pvc
